[mypy]
python_version = 3.11
strict = True
ignore_missing_imports = True
explicit_package_bases = True
plugins = pydantic.mypy


[tool.pydantic-mypy]
# Optional: Add plugin-specific settings here
# For example, to enforce strict typing in model __init__
init_typed = true
# To warn about untyped fields
warn_untyped_fields = true
